### PR TITLE
Fix: Add flip capability to images

### PR DESCRIPTION
**Pull request by luism-s**
Related to #796

### CODE REVIEW

**Comment by luism-s** [comment]
Hi @gitbrent, any prediction on when the 3.4.0 would come up?
Cheers

**Review by gitbrent — APPROVED** [review]
Tested and passed

**Comment by gitbrent** [comment]
Thanks @luism-s !

**Comment by gitbrent** [comment]
> Hi @gitbrent, any prediction on when the 3.4.0 would come up?
> Cheers

Before the end of the year for sure.

**Pull request merged**
