### PR TITLE
Added category crosses at property and its usage

### PR DESCRIPTION
**Pull request by parvezapathan**

### CODE REVIEW

**Comment by parvezapathan** [comment]
@gitbrent Could you please have a look at this PR, see if it's reasonable fix ?
Thanks
Parvez

**Comment by gitbrent** [comment]
@parvezapathan - sure, it looks easy enough to add. Can you provide an example of its use (what is this feature providing to charts)?

**Comment by benjaminpavone** [comment]
Hi
Any update on this PR ?

**Comment by gitbrent** [comment]
Thanks @parvezapathan

**Pull request merged**
