### PR TITLE
more text style: underline/strike/baseline

### PR DESCRIPTION
**Pull request by wangfengming**
- support underline type and color
- support strike type
- support baseline

### CODE REVIEW

**Comment by wangfengming** [comment]
https://github.com/gitbrent/PptxGenJS/issues/811

**Comment by wangfengming** [comment]
image

**Comment by gitbrent** [comment]
Thanks @wangfengming !

Screen Shot 2021-03-17 at 21 34 00

**Comment by wangfengming** [comment]
hi @gitbrent , I had made a mistake
```typescript
{
  	underline?: boolean | string | {
		type?: UnderlineType
		color?: HexColor
	}
}
```
should be 
```typescript
{
  	underline?: boolean | UnderlineType | {
		type?: UnderlineType
		color?: HexColor
	}
}
```

**Comment by gitbrent** [comment]
No problem - I changed it a bit during integration:

Screen Shot 2021-03-23 at 23 38 22

**Pull request merged**
