### PR TITLE
#399 feat: added new connector feature

### PR DESCRIPTION
**Pull request by lifejuggler**
added new anchor connector feature

### CODE REVIEW

**Comment by lifejuggler** [comment]
Just wondering if this can merged in soon?

**Comment by gitbrent** [comment]
Can you please provide an example for inclusion the in the `examples/pptxgenjs-demo.js` file and any accompanying documentation (markup/.md format).

You can use your modified code to gain the feature now, otherwise, the next NPM release is probably a few months out...

**Comment by lifejuggler** [comment]
> Can you please provide an example for inclusion the in the `examples/pptxgenjs-demo.js` file and any accompanying documentation (markup/.md format).
> 
> You can use your modified code to gain the feature now, otherwise, the next NPM release is probably a few months out...

sure I will put up an example today

**Comment by bartvanremortele** [comment]
Are connector's already integrated? I didn't find any information in the documentation and noticed this open PR. Any chance we can get this merged?

**Comment by gitbrent** [comment]
@bartvanremortele - not in its current form. The code has been completely rewritten in TS since this was added.

We also need the demos, documentation, etc.

**Comment by bartvanremortele** [comment]
@gitbrent, ok clear. I'll have a look over the weekend to see if I can port it and add the documentation and a demo.

**Comment by lifejuggler** [comment]
too outdated. going to reopen

**Pull request closed without merging**
