### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lucidlemon**
minor typo regarding alignment of an object

### CODE REVIEW

**Comment by ankon** [comment]
`pres` doesn't seem to be declared for the `ITextOpts` interface, and the constant name `AlignH.center` also seems to point to this being the `align` option.

https://github.com/gitbrent/PptxGenJS/blob/518667b3b23311275d9869846c90e1254a758c5f/types/index.d.ts#L1323-L1381

**Comment by gitbrent** [comment]
This is not correct. `align` is the proper way to align text...

**Comment by lucidlemon** [comment]
ah jesus my bad! i didn't mean to change the key - but the var `pptx` is undefined as you are referencing `pres`, fixed that now

**Comment by gitbrent** [comment]
@lucidlemon - thanks for the fix!

**Pull request merged**
