### PR TITLE
Added support for multi-level category axes

### PR DESCRIPTION
**Pull request by MariusOpeepl**
Supports AREA, BAR, BAR3D and LINE type charts.

In addition to providing a two-dimentional `labels` array in the `OptsChartData`, you also need to include the `catAxisMultiLevelLabels` chart option.

I've modified most of the XML generation to use a 2D `labels` internally, but providing a 1D array in the chart data is still possible, it'll get converted automatically to 2D.
PptxGenJS_Demo_Chart_20211011133528071

You can also have more than two levels of category axes:
PptxGenJS_Demo_Chart_20211011135641044

### CODE REVIEW

**Comment by gitbrent** [comment]
@MariusOpeepl 

1. can you please update this with your changes to the src/*.ts files and not the `dist` files - those are generated by webpack and are not mergable (see other pull reqs for examples)?
2. can you include sample code i can test with?

**Comment by MariusOpeepl** [comment]
@gitbrent 

1. Sure, I'll scrap the `dist` files.
2. The slides in the PR desc were made with the `modules/demo_chart.mjs` module, is it good enough if I include the sample code there, as a new slide?

On a side note, I'll remove the support for BAR3D, the chart itself doesn't make sense in multiple category layers.

**Comment by MariusOpeepl** [comment]
I added two demo slides with the charts that are in the PR desc, and I kept the BAR3D support, maybe someone does find a practical use for it with multiple category axes.

**Review by gitbrent — APPROVED** [review]

**Comment by gitbrent** [comment]
Thanks @MariusOpeepl, great work! 

Merged via Pull #1112

**Pull request closed without merging**
