### PR TITLE
Feature/slide background

### LINKED ISSUE #533: Is it possible to set an image as the background of the slide ?
I am currently working on a project aiming to create a PowerPoint thanks Python pptx. However I am trying to set an image as the background of the slide and I can’t seem to find the solution in the docs of Python pptx. Is it possible to set an image as background if so can someone help me ?

### PR DESCRIPTION
**Pull request by thomasowow**
Fixes #533 

Adds the feature to add a background image to a slide which is not a master.

Use:
```js
// The parameter can be exactly the same as one for a [master slide](https://gitbrent.github.io/PptxGenJS/docs/masters.html).
slide.background({
    src: 'some-url',
});
```

### CODE REVIEW

**Comment by readeral** [comment]
Hey @gitbrent - any chance this could be reviewed? Would be super handy.

**Comment by readeral** [comment]
Given the pull request is against the dist files, rather than the source, this pull request won't be merged. @thomasowow - the project has had a number of changes since this pull request was made, it's not immediately obvious where your code ought to go, but it might be worth opening a new PR?

**Comment by gitbrent** [comment]
Thanks @thomasowow 

Code is too old to merge, so i've added it manually.

Add a background image to any slide now:
```javascript
slide.background = {
  path: "https://raw.githubusercontent.com/gitbrent/PptxGenJS/master/demos/common/images/starlabs_bkgd.jpg"
}
```

**Comment by gnikolovski** [comment]
@gitbrent I tried testing this (_locally build from latest commit 7ae0765331dd1dc29784f11bec65134f2fab2faa_) and it's not working. 

I tried to add a background image like this:

`slide.background = {
  path: "https://raw.githubusercontent.com/gitbrent/PptxGenJS/master/demos/common/images/starlabs_bkgd.jpg"
}`

Am I doing something wrong?

**Comment by gitbrent** [comment]
@gnikolovski 

Make sure your version shows `3.3.0-beta`

```javascript
var pptx = new PptxGenJS();
var slide = pptx.addSlide();

slide.background = {path:'https://raw.githubusercontent.com/gitbrent/PptxGenJS/master/demos/common/images/starlabs_bkgd.jpg'}

slide.addText('background!', { x:1, y:1, w:'80%', h:1, align:'center', fill:pptx.SchemeColor.background2 });

pptx.writeFile('PptxGenJS-Test');
```

Screen Shot 2020-06-04 at 21 27 25

**Pull request closed without merging**
