### PR TITLE
#228 Placeholder object for Master Slides

### PR DESCRIPTION
**Pull request by conbow**
#228 
- Added new `placeholder` type to master slides objects
- Updated example/demo page to use new API
- Refactored some reused code
- Tested working with text, image, and charts

### CODE REVIEW

**Comment by gitbrent** [comment]
Hi @conbow 

Thanks for the patch.

The placeholder master slide's appear fine, but when adding other text to them, it's pushed to the very bottom and stuck into what looks like the last master slide's object - the footer bar in this case:

```
var pptx = new PptxGenJS();
pptx.setLayout('LAYOUT_WIDE');
pptx.defineSlideMaster({
  title : 'MASTER_SLIDE',
  margin: [0.5, 0.25, 1.25, 0.25],
  bkgd  : 'EEEEEE',
  objects: [
    {rect: { x:0, y:6.9, w:'100%', h:0.6, fill:'003b75' }},
    {text: { text:'S.T.A.R. Laboratories', options:{x:0.17, y:0.1, color:'FFFFFF'} }}
  ],
  slideNumber: { x:1.0, y:7.0, color:'FFFFFF' }
});

var slide = pptx.addNewSlide('MASTER_SLIDE');

// Bullets with indent levels
slide.addText(
  [
    { text:'1st line', options:{ fontSize:24, bullet:true, color:'99ABCC' } },
    { text:'2nd line', options:{ fontSize:36, bullet:true, color:'FFFF00', indentLevel:1 } },
    { text:'3rd line', options:{ fontSize:48, bullet:true, color:'0088CC', indentLevel:2 } }
  ],
  { x:1.5, y:1.5, w:6, h:2, margin:0.1, fill:'232323' }
);

pptx.save('PptxGenJS-patch');
```

screen shot 2018-07-09 at 23 03 55

Without including
screen shot 2018-07-09 at 23 07 04
 a master slide, the results are correct:

My merged, WIP branch is:
[pr/359](https://github.com/gitbrent/PptxGenJS/tree/pr/359)

**Comment by conbow** [comment]
@gitbrent Thanks for catching this. There was a missing condition that allowed the `p:ph` tag to be incorrectly added to objects that shouldn't have had it. I've pushed a fix for this, as well as some minor code styling fixes to more closely match the style of the repo.

**Comment by gitbrent** [comment]
Awesome, the placeholder ph tag checkin fixed the issue:

screen shot 2018-07-11 at 20 19 53

**Comment by gitbrent** [comment]
Thanks @conbow - great work on adding support for `placeholder`!

This was a feature that was much requested and sorely lacking. 

Patch #393 implements this feature.  The only change I made was to utilize `name` instead of `idx` for targeting objects to given placeholders.

```
// Master
pptx.defineSlideMaster({
    title: 'THANKS_SLIDE',
    bkgd: '36ABFF',
    objects: [
        { 'placeholder': { options:{ name:'thanksText', type:'title', x:0.0, y:0.9, w:'100%', h:1, color:'FFFFFF' } }}
    ]
});

// Add text to placeholder
slide.addText('Thank You!', { placeholder:'thanksText' });
```

**Comment by adong** [comment]
@gitbrent Could you give an example of using image with corp, as placeholder? 
I could not get it to work. Thank you.

**Pull request closed without merging**
