### PR TITLE
Minor bug fixes #452 #460

### LINKED ISSUE #452: Ability to specify numbered list format
First of all **Thank You** for such a great library!

Would you please advise on how hard would be to extend "bullet options" to allow to specify numbered list format?
At the moment all we can do is to specify that list is numbered, but we can't change which chars it will be using:
```
{
    bullet: {
        type: 'number'
    } 
}
```

In particular I need to built something like:
image

 `indentLevel` already allows to set indent, but "child" lists are using the same numbering format
image

### PR DESCRIPTION
**Pull request by mayvazyan**
This one aims to implement #452

### CODE REVIEW

**Comment by gitbrent** [comment]
Hi @mayvazyan 

This change breaks existing functionality.  Multi-line text is now rendered as a single line:

```
slide.addText(
    '***Line-Break/Multi-Line Test***\n\nFirst line\nSecond line\nThird line',
    { x:1, y:1, w:11, h:2, valign:'m', align:'c', color:'6c6c6c', fill:'F2F2F2' }
);
```
screen shot 2018-12-31 at 12 05 15

**Comment by ReimaFrgos** [comment]
@gitbrent @mayvazyan I have submitted #500 based on this PR that resolves the issue with breaking existing functionality.

I have not included the list code. Just the alignment/breakLine patch.

Have tested against the existing test cases and works OK.

The following code shows an example of breakLine:true, \n, and alignment all being used together.
```
slide.addText([
{ text:'1st\nline',options:{ fontSize:24, fontFace:'Courier New', color:'99ABCC' } },
{ text:'2nd line', options:{ fontSize:36, fontFace:'Arial',       color:'FFFF00', breakLine:true } },
{ text:'3rd line', options:{ fontSize:48, fontFace:'Verdana',     color:'0088CC' } },
{ text:'4th line', options:{ fontSize:38, fontFace:'Arial',       color:'FFFF00', strike:true } },
{ text:'5th\nline',options:{ fontSize:36, fontFace:'Courier New', color:'99ABCC' } }
],
{ x:0.5, y:0.85, w:6, h:4, margin:0.1, fill:'232323', align:'c'});
```

**Comment by ReimaFrgos** [comment]
Actually. Ignore my comment/ PR for now. There are still a few scenarios that this doesn't handle.

**Comment by gitbrent** [comment]
Okay, just let me know when you're done.

Thanks very much for the effort!

**Comment by gitbrent** [comment]
Version 3.0 has major text generation fixes - let's create new issues/patches as needed for the TypeScript code.

**Pull request closed without merging**
