### PR TITLE
Add ability to start slide numbers with value other than 1 (Issue #288)

### LINKED ISSUE #288: Slide number start from 0
Hello All,
  Now I am getting slide number from 1 to N. This is ok. So my question is that how to start slide number from 0 to N.
Thanks in advance!
Shrikant
shri.bhongade@gmail.com

### PR DESCRIPTION
**Pull request by kumaarraja**
Removed pageNum variable from addNewSlide API as it is not being used much and starting slide number from 0 to N (as a fix for #288).

### CODE REVIEW

**Comment by gitbrent** [comment]
Have you validated that this creates Slides that start with number "0"?

**Comment by kumaarraja** [comment]
I have validated this and found no issues with these changes.

**Comment by gitbrent** [comment]
Can you show me the test code and the resulting PPTX showing a slide with a "0" page number?

**Comment by kumaarraja** [comment]
Oops! Sorry, I only made sure to return page number which starts with "0". I didn't modify slide XML to show from '0'.

**Comment by kumaarraja** [comment]
Hi @gitbrent , I reverted previous changes and added changes for slide number (configurable) to start from 0.

**Comment by gitbrent** [comment]
Closing as this still strikes me as odd, and there's not a lot of users requesting it.

**Pull request closed without merging**
