### PR TITLE
Added Text Direction to Table Cell

### PR DESCRIPTION
**Pull request by jarylchong**
Added support for text direction (vert) in table cells.

### CODE REVIEW

**Comment by gitbrent** [comment]
Thanks for the patch @jarylchong 

Would you mind adding some test code here showing each of the options being used?

**Comment by jarylchong** [comment]
Do you mean something like this?

```
		slide.addTable([
			[
				{ text:"vert: 'eaVert'",         options: { vert: 'eaVert' } },
				{ text:"vert: 'horz'",           options: { vert: 'horz' } },
				{ text:"vert: 'mongolianVert'",  options: { vert: 'mongolianVert' } },
				{ text:"vert: 'vert'",           options: { vert: 'vert' } },
				{ text:"vert: 'vert270'",        options: { vert: 'vert270' } },
				{ text:"vert: 'wordArtVert'",    options: { vert: 'wordArtVert' } },
				{ text:"vert: 'wordArtVertRtl'", options: { vert: 'wordArtVertRtl' } }
			]],
			{ x:0.6, y:1.25, w:12, h:3, fontSize:24, border:{pt:'1'}, fill:{color:'F1F1F1'} }
		);
```

**Review by gitbrent — APPROVED** [review]

**Review by gitbrent — CHANGES_REQUESTED** [review]
I do not see `vert` in the spec, nor is there an option in the PPT UI for this...?

**Comment by gitbrent** [comment]
Closing as this does not exist in the spec and does not seem to be implementable.

**Comment by jarylchong** [comment]
Oops, I let this slip between other things.

Here's a link to this vertical text direction from Microsoft: 
https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.drawing.tablecellproperties.vertical?view=openxml-2.8.1

That documentation above says the values are defined by the `ST_TextVerticalType`, so here's a list of the possible values for `ST_TextVerticalType` (taken from "ECMA-376, part 1" here: https://www.ecma-international.org/publications-and-standards/standards/ecma-376/ )
image



Lastly, here is the option in the PPT UI itself:
image

If all this is unacceptable, may I know which spec you are referencing?

**Pull request closed without merging**
