### PR TITLE
Single data set with a custom color should not create legends for each category

### PR DESCRIPTION
**Pull request by tvt**
When creating a bar chart with a single data set and setting custom colors each category gets a legend-entry. See #285 for last time that happened.

I guess the idea is that if you pass in an array of colors to a single data set, that means that you want each category to have a different color.

I think it would make more sense if creating legend entries for categories were an option that could be set.
This solution instead add a check to avoid trying to color each category, if only a single color is passed.

### CODE REVIEW

**Comment by tvt** [comment]
Hi @gitbrent, anything else you need from me to help get this merged?

**Comment by gitbrent** [comment]
@tvt - got any test cases?

**Comment by tvt** [comment]
@gitbrent sure:

```
const slide = pptx.addNewSlide();
var data = [
    {
        name: 'Sample',
        labels: [0, 1],
        values: [2, 5],
    },
];

slide.addChart(pptx.charts.BAR, data, { showLegend: true, chartColors: ['0000FF'] });
pptx.writeFile();
```

Gives the output in Powerpoint 2016:
screenshot_2020-12-28-105836

**Review by gitbrent — APPROVED** [review]

**Comment by gitbrent** [comment]
Thanks @tvt !

**Pull request merged**
