### PR TITLE
Add Alt Text to charts

### PR DESCRIPTION
**Pull request by yorch**
Alt text for charts is not currently populated, so it's not fully accesible. Adding a `descr` property to the charts translates to Alt Text box in PPT.

### CODE REVIEW

**Comment by gitbrent** [comment]
Thanks @yorch 

Screen Shot 2021-04-26 at 22 18 33

Screen Shot 2021-04-26 at 22 17 56

**Comment by yorch** [comment]
@gitbrent awesome, thank you!

**Comment by yorch** [comment]
@gitbrent just realized that the [commit with the change](https://github.com/gitbrent/PptxGenJS/commit/9f38c29ff3040d26fa3afec997b4f46a197d1c46) does not include `altText` support for images as I included in this PR (https://github.com/gitbrent/PptxGenJS/pull/848/files#diff-2e10387a0f5301958ef328618c21a1df1de827655aec5abbe99bf0ba59631f5dR1785-R1789). Is this is something you can include?
Thanks

**Comment by gitbrent** [comment]
@yorch - quite correct. I meant to modify the current alt text on Images, but i got distracted. It's always had an alt text value of the image path, so i've set to where it uses `altText` if provided, then the path if none.

Screen Shot 2021-05-09 at 16 16 29

**Comment by yorch** [comment]
@gitbrent great, thanks so much! looking forward for a new version :D

**Comment by yorch** [comment]
@gitbrent just saw a new version was released, thanks, been waiting for this new release for a while. Unfortunately, the TS definition for `addImage` is not correct, it's missing the `altText` option.

It's here:
https://github.com/gitbrent/PptxGenJS/blob/9e6aab8e5b5900b3ab476d2c442c69076250471f/src/core-interfaces.ts#L422

But it's not here:
https://github.com/gitbrent/PptxGenJS/blob/9e6aab8e5b5900b3ab476d2c442c69076250471f/types/index.d.ts#L1241

Thanks again

**Comment by gitbrent** [comment]
@yorch Oops! Thanks for letting me know. v3.7.1 has been released with `altText` included in the defs file.

**Comment by yorch** [comment]
@gitbrent thanks! much appreciated!

**Pull request closed without merging**
